### ISSUE TITLE
Logout Bug

### ISSUE THREAD

**Issue by abhinavshukla01** [Programming-Addicts/BookSplore#25]
When we are logging out from the account and again clicking on Get Started button then still it is showing me logged in.

**Comment by classPythonAddike** [comment]
Thats a feature of google oauth. If you're only signed in with one google account, google with automatically choose that account with prompting you. So when you log out, then click `Get Started` in the home page, it redirects you to the login page, and then google automatically signs you in.

**Comment by classPythonAddike** [comment]
Thanks for reporting this issue! We will reproduce this bug and fix it soon.

**Comment by classPythonAddike** [comment]
Unfortunately, I'm not able to reproduce this bug at all. Could you try clearing the cookies for that page and then try again?
